### ISSUE TITLE
Folders starting with underscore on github pages

### ISSUE THREAD

**Issue by hbr** [ocaml/odoc#955] opened 2023-04-19 05:59 UTC
I have run into the following problem. I have an ocaml project where I generate the documentation with `odoc`. `odoc` generates the directory `_odoc_support` where files like `odoc.css` etc. are put.

Unfortunately github pages with jekyll considers directories starting with underscore as special and does not copy them to the final site. In that case the rendering of the documentation does not look nice.

I have found a workaround by putting an empty file called `.nojekyll` at the root of my github pages. But in the long run it would be better if `odoc` did not generate directories starting with underscore.

Regards
Helmut

**Comment by dbuenzli** [comment] 2023-04-19 08:14
> But in the long run it would be better if `odoc` did not generate directories starting with underscore.

We need a name that cannot be accessed via the module or `.mld` namespace. The current name satisfies this property. I'm not sure there's really better alternative here. 

Given that other people with other systems seem to struggle with this I'd rather say the problem is with jekyll here.

**Comment by jonludlam** [comment] 2023-04-19 08:18
odoc itself supports putting the support files wherever you like - it's up to the driver to tell odoc to do that though. I'm guessing you're using dune to create the docs? In which case, dune could be updated to be able to specify the location of the support directory.

**Comment by hbr** [comment] 2023-04-19 08:26
> odoc itself supports putting the support files wherever you like - it's up to the driver to tell odoc to do that though. I'm guessing you're using dune to create the docs? In which case, dune could be updated to be able to specify the location of the support directory.

I am using dune 3.7.1 which is the most recent version. How can I tell dune the location of the support directory?

**Comment by jonludlam** [comment] 2023-04-19 08:28
You can't, it's hardcoded right now - see my link above. Dune would need modification in order to do this, so your issue is with dune, not odoc :-) I'll close this, but feel free to make an issue for dune.

**Comment by dbuenzli** [comment] 2023-04-19 08:29
For xref there is one here https://github.com/ocaml/dune/issues/7364

**Closed by jonludlam** 2023-04-19 08:28 UTC
