### ISSUE TITLE
Infinite loop on unclosed table 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#1063] opened 2023-12-14 22:08 UTC
It's in the title. Repro case:

```
> ocamlc --version                                                                                                                                                    
4.14.1
> odoc --version
v2.3.0
> cd /tmp
> cat - > a.mli <<EOF
(**

{table
{tr {th id} {th bla}} *)
EOF
> ocamlc a.mli
> ocamlc -bin-annot a.mli
> odoc compile --pkg 'a' -o a.odoc a.cmti 
⏳💀
```

**Comment by panglesd** [comment] 2023-12-15 12:36
I think it is a duplicate of #1043, which has been solved in #1050. Included in the just released last version of odoc! Please reopen if that's not the case.

**Closed by panglesd** 2023-12-15 12:36 UTC
Labels: bug
