### ISSUE TITLE
Please stop displaying the `odoc should not generate html ...` warning

### ISSUE THREAD

**Issue by diml** [ocaml/odoc#158] opened 2018-07-10 13:08 UTC
I'm seeing this warning often when building documentation with odoc. Given that this is not a warning users can remove by modyifing their own code, I suggest to stop displaying it.

**Comment by rizo** [comment] 2018-09-20 17:46
This seems to be a duplicate of https://github.com/ocaml/odoc/issues/169 resolved in https://github.com/ocaml/odoc/commit/00b60464a2d9e3409b17e60cc91aa221612431c4.

**Closed by rizo** 2018-09-20 17:46 UTC
Labels: command line, good first issue
