### ISSUE TITLE
Fail to build from Makefile following CONTRIBUTING instructions

### ISSUE THREAD

**Issue by AllanBlanchard** [ocaml/odoc#721] opened 2021-09-03 15:59 UTC
I tried to follow the instructions on https://github.com/ocaml/odoc/blob/master/CONTRIBUTING.md .

Configuration:
- Ubuntu 20.04
- fresh opam switch 4.12.0 (only a ocaml-lsp-server installed).

This part:

```
git clone --recurse-submodules https://github.com/ocaml/odoc.git
cd odoc
opam pin add --no-action odoc .
opam install --with-test --deps-only odoc
opam install --deps-only mdx
```

seems to execute correctly, but `make` gives me the following errors:

```
$ make
dune build  
File "cases/markup.mli", line 157, characters 4-16:
'{!modules ...}' should not be empty.
File "ocamlary.cmti":     
Failed to compile expansion for module type expression identifier((root Ocamlary).With10.T.M, false).S OpaqueModule
[ ... and more like this ... ]
File "type.odoc":         
Couldn't find the following modules:
  CamlinternalFormatBasics
File "ocamlary.odoc":     
Couldn't find the following modules:
  Stdlib
File "doc/dune", line 12, characters 8-22:
12 |    (run ocaml-mdx-test %{x})
             ^^^^^^^^^^^^^^
Error: Program ocaml-mdx-test not found in the tree or in PATH
 (context: default)
File "test/xref2/refs/dune", line 8, characters 7-21:
8 |   (run ocaml-mdx-test --prelude=%{dep:../lib/prelude.ml} -o %{targets}
           ^^^^^^^^^^^^^^
Error: Program ocaml-mdx-test not found in the tree or in PATH
 (context: default)
File "test/xref2/resolve/dune", line 6, characters 7-21:
6 |   (run ocaml-mdx-test --prelude=%{dep:../lib/prelude.ml} -o %{targets}
           ^^^^^^^^^^^^^^
Error: Program ocaml-mdx-test not found in the tree or in PATH
 (context: default)
File "test/xref2/strengthen/dune", line 6, characters 7-21:
6 |   (run ocaml-mdx-test --prelude=%{dep:../lib/prelude.ml} -o %{targets}
           ^^^^^^^^^^^^^^
Error: Program ocaml-mdx-test not found in the tree or in PATH
 (context: default)
File "test/xref2/subst/dune", line 6, characters 7-21:
6 |   (run ocaml-mdx-test --prelude=%{dep:../lib/prelude.ml} -o %{targets}
           ^^^^^^^^^^^^^^
Error: Program ocaml-mdx-test not found in the tree or in PATH
 (context: default)
make: *** [Makefile:14 : build] Erreur 1
```

If I type `make` again, I only get the errors starting from `File "doc/dune", line 12, characters 8-22:`. I checked my `opam` packages against those listed by the Ubuntu 20.04 CI, and all versions are fine (as well as dependencies according to `opam depext`. I naively tried to install `mdx` from `opam`, bu I get an error related to `odoc.parser`:

```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of mdx failed at "/home/allanb/.opam/opam-init/hooks/sandbox.sh build dune build -p mdx -j 11 @install".

#=== ERROR while compiling mdx.1.10.1 =========================================#
# context     2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.0 | https://opam.ocaml.org#5c5a526e
# path        ~/.opam/odoc/.opam-switch/build/mdx.1.10.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p mdx -j 11 @install
# exit-code   1
# env-file    ~/.opam/log/mdx-718961-e7966f.env
# output-file ~/.opam/log/mdx-718961-e7966f.out
### output ###
# File "lib/dune", line 7, characters 49-60:
# 7 |  (libraries astring csexp fmt logs ocaml-version odoc.parser re result str))
#                                                      ^^^^^^^^^^^
# Error: Library "odoc.parser" not found.
# Hint: try:
#   dune external-lib-deps --missing --no-config --root . --ignore-promoted-rules --default-target @install --always-show-command-line --promote-install-files --release --only-packages mdx -p mdx --profile release -j 11 @install
```

which seems to be correctly installed:

```
$ opam install odoc-parser
[NOTE] Package odoc-parser is already installed (current version is 0.9.0).
```

Do you have any hint on what I am doing wrong?

**Comment by dbuenzli** [comment] 2021-09-03 16:08
I think you are missing an `eval $(opam env)`.

**Comment by jonludlam** [comment] 2021-09-03 16:33
Right now you'll need the development version of mdx - try

```
 opam pin add mdx --dev-repo 
```

and see if that works? The issue is that odoc's parser was removed from odoc (where it was `odoc.parser`) and turned into a separate package (`odoc-parser`), and the required change in mdx hasn't yet been released.

**Comment by AllanBlanchard** [comment] 2021-09-06 06:16
Indeed the development version works, thank you!

I still had to install also `bos` some tests were failing because it was missing. I also have a test that fails:

````diff
--- a/doc/driver.md
+++ b/doc/driver.md.corrected
@@ -305,6 +305,14 @@ let compile_mlds () =
         ) all_libraries in
     List.map Fpath.v ("page-odoc.odoc" :: "page-deps.odoc" ::  odocs @ extra_odocs)
 ```
+```mdx-error
+Line 5, characters 7-94:
+Warning 10: this expression should have type unit.
+Line 6, characters 7-76:
+Warning 10: this expression should have type unit.
+Line 13, characters 11-51:
+Warning 10: this expression should have type unit.
+```
````

But at least I can build `odoc` and execute most of the tests.

**Comment by dbuenzli** [comment] 2022-06-09 09:49
I followed them yesterday and they worked so I guess we can close this.

**Closed by dbuenzli** 2022-06-09 09:49 UTC
