### ISSUE TITLE
Allow level-1 headings in mli files

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#141] opened 2018-05-28 00:05 UTC
I can't get any proper documentation output on 4.06.1. This happens even after pinning to dune master, which has an [issue](https://github.com/ocaml/dune/issues/791) which seemed to be similar to what I'm seeing.

Steps to reproduce:

1. Install 4.06.1 and dune/jbuilder.
2. Clone https://github.com/rizo/order.
3. Run `jbuilder build @doc`.
4. Open `_build/default/_doc/_html/index.html`
5. Click on the `order` package. 
6. Click on the `Order` module.
7. Click on the `Ordered` interface. You should get a 404 -- this resource wasn't created.

Running on `odoc` itself produces similar issues -- nothing is created inside the odoc package.

(To try out pinning to `dune` master, you currently have to use `dune` as the package name and prompt opam to create it, or both `dune` and `jbuilder` will not be available.)

**Comment by bobbypriambodo** [comment] 2018-05-28 02:09
I can reproduce this using the steps given above. Some pages are not generated.

| dune ver.       | odoc ver.        | docs working? |
| ------------- | ------------- | -------------- |
| 1.0+beta20    | 1.2.0               | Yes                   |
| dev                 | 1.2.0               | Yes                   |
| 1.0+beta20    | dev                 | No                    |
| dev                 | dev                 | No                    |

FWIW, there were several warnings emitted when using `odoc.dev`:

```
$ jbuilder build @doc
        odoc _doc/_odoc/lib/order/Order.odoc
File "src/Order.mli", line 322, character 53 to line 323, character 12:
line break is not allowed in '[...]' (code)
File "src/Order.mli", line 364, character 61 to line 365, character 31:
line break is not allowed in '[...]' (code)
File "src/Order.mli", line 389, character 75 to line 390, character 8:
line break is not allowed in '[...]' (code)
```

But even after fixing those errors (deleting the line breaks) the docs are still not generated properly, now without warnings or errors.

**Comment by rizo** [comment] 2018-05-30 20:41
@bluddy thanks for reporting this and sorry for the delay.

This is still related to the `{1 ...}` error. The mentioned issue in dune has nothing to do with this because it's odoc that has this restriction. The submitted [fix in dune](https://github.com/ocaml/dune/commit/b2dd90484776774e5f9f2204ab5d9ff0bb9e575b) simply stops using title-level headings avoiding the restriction.

I've also "fixed" this now in the `order` library by pushing a change that doesn't use `{1 ...}`.

@aantron I think we should relax this restriction somehow.

**Comment by dbuenzli** [comment] 2018-05-30 20:59
> @aantron I think we should relax this restriction somehow.

See [here](https://github.com/ocaml/odoc/pull/139#issuecomment-393316557) for a rationale.

**Comment by aantron** [comment] 2018-05-30 21:21
And [here](https://github.com/ocaml/odoc/pull/139#issuecomment-393320722) for a counterargument, I guess we should move that discussion here.

The current behavior is supposed to be to clamp headings to levels [2-4] in mlis, [1-4] for the first title in a mld, issue a warning, and continue parsing. Obviously, there is some kind of bug with that, but I don't have time to take a look immediately. odoc shouldn't be stopping with a fatal error. We shared some links in chat about the code that might be at fault.

**Comment by aantron** [comment] 2018-05-30 21:30
@Octachron also has a note about the history of `{1` in ocamldoc [here](https://github.com/ocaml/odoc/pull/139#issuecomment-393322952).

I'd also like to add that in case we support LaTeX output, [2-4] map onto `\section`, `\subsection`, and `\subsubsection` quite nicely.

**Comment by dbuenzli** [comment] 2018-05-30 21:57
As @octachron mentioned starting with `{2` is very unnatural in `.mli` files and I find the idea that you can simply ignore practice and educate users a bit arrogant. I have other things to do than changing in hundreds of published and unpublished `.mli` section headers to follow an unnatural convention for no obvious return.

I think a simpler way of achieving the stylistic unification you want between `.mld` and `.mli` without disturbing existing practice too much would be: 

1. Restrict usage of `{0` to a single usage *and only* in `.mld` files. This can then defines the contents of the `title` element. Stylistically this will matches the header for the module name in `.mli` files that is not definable by the user in these files.
2. In `.mli` files warn on `{0` usage and simply map to `{1`. I don't think that he fact that `{0` is available is a well known fact (I didn't until today).

**Comment by lpw25** [comment] 2018-05-30 22:09
Another approach for `mld` files would be to support a `@title` tag. So users would just write:
```
@title This is the title
...
```
This somewhat depends on how the parser handles tags. The old parser would have placed the entire document under the `@title` tag with this scheme -- which is obviously not what we want -- but I suspect the new parser might be a little more sane in this regard.

**Comment by samoht** [comment] 2018-05-30 22:09
I am not really looking forward to replace every occurence of `{1` by `{2` in the hundreds of mirage packages.  And it seems that the OCaml's stdlib will also needs to be fixed.

I understand the rational of simplifying the ocamldoc/html mapping, but in this case I am not sure what we really gain. I always thought of these numbers as a way to classify section and sub-sections inside a file, not as a mapping to html sections. Starting by numbering these sections using `2` seems a bit weird.

**Comment by aantron** [comment] 2018-05-31 16:34
I'm not committed to clamping to [2-4] by any means, but I would like to point out that odoc's own parser could be easily modified to walk through documentation in bulk and generate diffs for replacing `{1` by `{2`, and adjusting lower-level sections accordingly. Of course, it's still work that might not be worth it, but you wouldn't have to manually replace every section level number.

**Comment by dbuenzli** [comment] 2018-06-03 20:52
@aantron as others mention writing `{2` in your `.mli` files is really not natural, whether or not you can automate the transition (besides you'd still break the look of the documentation of these packages until they release a new version).

**Comment by dbuenzli** [comment] 2018-06-13 17:00
I'll soon start writing `.mld` files. I think it would be nice to have a resolution on this so that people don't have to change their files in the future.

Personally I think that [this proposal](https://github.com/ocaml/odoc/issues/141#issuecomment-393333054) is not too bad. I could do with @lpw25's proposal but I'd rather use sectioning element everywhere and finally I would really not like to write `{2` in my `.mli` files.

**Comment by dbuenzli** [comment] 2018-06-13 17:35
@rizo I don't have a strong opinion on that one as long as they can be distinguished. 

I would however find it more logical not to use the same level for different heading levels. Who cares if `{1` gets mapped to `h2`, only the stylesheet designer and that's no horribly complicated to see no ? 

 Suppose e.g. you'd like to concatenate the result of multiple pages module pages, if you don't distinguish `{0` from `{1`, the html5 outline algorithm would show everything at the same level which feels a bit wrong.

**Comment by aantron** [comment] 2018-06-13 17:54
@rizo I was planning to remove the excessive `<section>` elements because not having them makes some kinds of CSS techniques easier.

**Comment by aantron** [comment] 2018-06-13 17:55
(I would reserve the multiple `<h1>` on a page for when we inline one module page into another, if ever).

**Comment by rizo** [comment] 2018-06-13 18:11
@dbuenzli You're right, it's a purely conceptual concern really.

I agree that ultimately the outline generation should be taken into consideration when deciding this. Althogh I don't really see why we'd want to concatenate multiple pages... book generation? :)

@aantron can you explain what in CSS becomes easier with less sections? I think _some_ sections are unnecessary but overall I like having them.

**Comment by aantron** [comment] 2018-06-13 20:13
@rizo one thing I've often done in CSS is adjust the vertical spacing of a section depending on what precedes it, with selectors like `.foo + h2`. Having `<section>` tags can disrupt that, in ways that are difficult to account for, especially at the end of a section (across a `</section>` tag).

**Comment by dbuenzli** [comment] 2018-06-14 06:51
FWIW previous generations of `odoc` had excessive `div`itiss and effectively made it difficult to style (see this [issue and suggestion](https://github.com/ocaml/odoc/issues/23#issue-178073897)).

**Closed** 2018-10-19 22:42 UTC
