### ISSUE TITLE
Stop-comment at the beginning of a mli generates wrong outputs

### ISSUE THREAD

**Issue by Halbaroth** [ocaml/odoc#891] opened 2022-08-30 12:01 UTC
I came across some bugs in the last release (2.1.1) of odoc and Dune 3.4.1 while using the stop-comment instruction.

In a mli file: 
```ocaml
(**/**)
exception ErrorA
(**/**)

exception ErrorB
```
produces a string /* at the beginning of the html doc and shows ``exception ErrorA`` and hides ``exception ErrorB``.

If I add an empty odoc comment at the beginning of the file or a valid ocaml expression, I got the expected behavior (unless this expression is a ordinary comment): 
```ocaml
(** *)
(**/**)
exception ErrorA
(**/**)

exception ErrorB
```
or
```ocaml
module Fmt = Format
(**/**)
exception ErrorA
(**/**)

exception ErrorB
```

Now, if I try to hide a module abbreviation, the result is even worse: 
```ocaml
(**/**)
module Fmt = Format
(**/**)

exception ErrorA
exception ErrorB
```
The above code produces only the buggy string /*. The two exceptions are not displayed.

I think the issue is related to #841.

**Comment by dbuenzli** [comment] 2022-08-30 12:05
Thanks for the report. Duplicate of https://github.com/ocaml/odoc/issues/666

**Closed by dbuenzli** 2022-08-30 12:05 UTC
