### ISSUE TITLE
Internal error, uncaught exception:

### ISSUE THREAD

**Issue by hhugo** [ocaml/odoc#1007] opened 2023-09-27 05:45 UTC
Spotted in jsoo CI https://github.com/ocsigen/js_of_ocaml/actions/runs/6318919406/job/17158899539

```
(cd _build/default/lib/js_of_ocaml/.js_of_ocaml.objs/byte && /home/runner/work/js_of_ocaml/js_of_ocaml/_opam/bin/odoc compile -I . -I ../../../../_doc/_odoc/pkg/js_of_ocaml -I ../../../runtime/.jsoo_runtime.objs/byte --pkg js_of_ocaml -o js_of_ocaml__Intl.odoc js_of_ocaml__Intl.cmti)
odoc: internal error, uncaught exception:
      File "src/loader/cmi.ml", line 1063, characters 26-32: Assertion failed
      Raised at Odoc_loader__Cmi.read_signature_noenv.loop in file "src/loader/cmi.ml", line 1063, characters 26-38
      Called from Odoc_loader__Cmti.read_include in file "src/loader/cmti.ml", line 748, characters 26-106
      Called from Odoc_loader__Cmti.read_signature.(fun) in file "src/loader/cmti.ml", line 787, characters 24-61
      Called from Stdlib__List.fold_left in file "list.ml", line 123, characters 24-34
      Called from Odoc_loader__Cmti.read_signature in file "src/loader/cmti.ml", line 785, characters 4-127
      Called from Odoc_loader__Cmti.read_module_type_maybe_canonical in file "src/loader/cmti.ml", line 578, characters 8-74
      Called from Odoc_loader__Cmti.read_module_declaration in file "src/loader/cmti.ml", line 620, characters 10-133
      Called from Odoc_loader__Cmti.read_signature_item in file "src/loader/cmti.ml", line 684, characters 14-51
      Called from Odoc_loader__Cmti.read_signature.(fun) in file "src/loader/cmti.ml", line 787, characters 24-61
      Called from Stdlib__List.fold_left in file "list.ml", line 123, characters 24-34
      Called from Odoc_loader__Cmti.read_signature in file "src/loader/cmti.ml", line 785, characters 4-127
      Called from Odoc_loader__Cmti.read_interface in file "src/loader/cmti.ml", line 800, characters 4-74
      Called from Odoc_loader.read_cmti in file "src/loader/odoc_loader.ml", line 98, characters 34-70
      Called from Odoc_loader.wrap_errors.(fun) in file "src/loader/odoc_loader.ml", line 164, characters 10-14
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.resolve_and_substitute in file "src/odoc/compile.ml", line 87, characters 4-31
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.compile.(fun) in file "src/odoc/compile.ml", line 239, characters 6-136
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 22, characters 12-19
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

**Comment by shym** [comment] 2023-10-06 13:10
I see the same error with odoc 2.3 in a fresh Opam switch with OCaml 5.1:
```
$ odoc compile --pkg ocaml -o /tmp/test.odoc ~/.opam/5.1/lib/ocaml/ocamldoc/odoc_scan.cmi
odoc: internal error, uncaught exception:
      File "src/loader/cmi.ml", line 1067, characters 26-32: Assertion failed
      Raised at Odoc_loader__Cmi.read_signature_noenv.loop in file "src/loader/cmi.ml", line 1067, characters 26-38
      Called from Odoc_loader__Cmi.read_signature in file "src/loader/cmi.ml" (inlined), line 1075, characters 9-46
      Called from Odoc_loader__Cmi.read_interface in file "src/loader/cmi.ml", line 1080, characters 14-51
      Called from Odoc_loader.read_cmi in file "src/loader/odoc_loader.ml", line 182, characters 8-96
      Called from Odoc_loader.wrap_errors.(fun) in file "src/loader/odoc_loader.ml", line 192, characters 10-14
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.resolve_and_substitute in file "src/odoc/compile.ml", line 114, characters 8-57
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.compile.(fun) in file "src/odoc/compile.ml", line 297, characters 6-180
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 22, characters 12-19
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

**Comment by tmcgilchrist** [comment] 2023-10-12 22:46
Reproducible with odoc.2.2.1 / 2.3.0 and OCaml 5.1, steps to reproduce:

```
$ opam switch create . 5.1.0 --no-install 
$ opam install odoc.2.2.1
$ odoc compile _opam/lib/ocaml/ocamldoc/odoc_scan.cmi
odoc: internal error, uncaught exception:
      File "src/loader/cmi.ml", line 1063, characters 26-32: Assertion failed
      Raised at Odoc_loader__Cmi.read_signature_noenv.loop in file "src/loader/cmi.ml", line 1063, characters 26-38
      Called from Odoc_loader__Cmi.read_signature in file "src/loader/cmi.ml" (inlined), line 1071, characters 9-46
      Called from Odoc_loader__Cmi.read_interface in file "src/loader/cmi.ml", line 1076, characters 14-46
      Called from Odoc_loader.read_cmi in file "src/loader/odoc_loader.ml", line 155, characters 8-96
      Called from Odoc_loader.wrap_errors.(fun) in file "src/loader/odoc_loader.ml", line 164, characters 10-14
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.resolve_and_substitute in file "src/odoc/compile.ml", line 87, characters 4-31
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.compile.(fun) in file "src/odoc/compile.ml", line 239, characters 6-136
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 22, characters 12-19
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
$ opam install odoc.2.3.0      
$ odoc compile _opam/lib/ocaml/ocamldoc/odoc_scan.cmi                                   
odoc: internal error, uncaught exception:
      File "src/loader/cmi.ml", line 1067, characters 26-32: Assertion failed
      Raised at Odoc_loader__Cmi.read_signature_noenv.loop in file "src/loader/cmi.ml", line 1067, characters 26-38
      Called from Odoc_loader__Cmi.read_signature in file "src/loader/cmi.ml" (inlined), line 1075, characters 9-46
      Called from Odoc_loader__Cmi.read_interface in file "src/loader/cmi.ml", line 1080, characters 14-51
      Called from Odoc_loader.read_cmi in file "src/loader/odoc_loader.ml", line 182, characters 8-96
      Called from Odoc_loader.wrap_errors.(fun) in file "src/loader/odoc_loader.ml", line 192, characters 10-14
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.resolve_and_substitute in file "src/odoc/compile.ml", line 114, characters 8-57
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.compile.(fun) in file "src/odoc/compile.ml", line 297, characters 6-180
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 22, characters 12-19
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44      
```

Not present in OCaml 4.14.1 or earlier.

**Comment by Julow** [comment] 2023-11-03 15:15
This seems to be fixed by https://github.com/ocaml/odoc/pull/1018

**Closed by Julow** 2023-11-03 15:15 UTC
