### ISSUE TITLE
custom css and html header for building documentation with dune

### ISSUE THREAD

**Issue by tachukao** [ocaml/odoc#322] opened 2019-02-24 21:56 UTC
When using dune to build documentation with `dune build @doc`, is there an easy way to 
1. pass in a custom css files to replace the default `odoc.css`, and or
2.  insert segments into the headers of all generated headers files (e.g. to load mathjax in the header)?

Currently, I have opted for manually changing the generated `odoc.css` and `highlight.pass.js` file in `_build/_default/_doc/_html/`, but it would be good to have a less hacky solution.

I'm guessing a solution would probably involve raising an issue with dune as well, but I was wondering if you have insights on how best to approach this from `odoc`'s side. Thank you for your help!

**Comment by aantron** [comment] 2019-02-25 14:21
Right now, odoc itself accepts `--theme-uri=DIR`, with `DIR` containing an alternative `odoc.css`. There is no direct way to alter the `<head>`. I also don't think Dune offers a way to pass `--theme-uri` to odoc. So, I recommend to continue manually copying in your own `odoc.css` and hacked `highlight.pack.js` file, until we solve this issue properly.

On odoc's side, we just need to add the right options and/or environment variables.

**Comment by tachukao** [comment] 2019-02-25 14:32
thanks @aantron, that's good to know.

**Comment by mseri** [comment] 2019-02-25 14:39
If you are happy to get a PR from us about this, and maybe mentor us on what needs to be done, I am sure somebody could pick this item up

**Comment by trefis** [comment] 2019-02-25 14:56
We should just update [dune's documentation stanza](https://dune.readthedocs.io/en/latest/documentation.html?highlight=odoc#documentation-stanza) to add a `theme-uri` field.

**Comment by mseri** [comment] 2019-02-25 14:58
At least in our case, we need also to introduce a new `--js-uri` (or whatever better name) to include mathjax. Then expose both options in the documentation stanza.

**Comment by mseri** [comment] 2019-02-25 15:15
I see, I thought that installing the correct js locally would have been enough for that to work. I am all for proper latex support then

**Comment by mseri** [comment] 2019-02-25 15:17
Maybe we should close this as duplicate of #123 and consider extending the documentation stanza as @trefis suggests

**Comment by tachukao** [comment] 2019-02-25 15:35
> I don't think this is a good idea. If your docset starts relying on specific JavaScript files to render correctly it will not work e.g. when the library is installed and its documentation is rendered via odig in a user's install base (e.g. [here](https://b0-system.github.io/odig/doc/owl-base/index.html)).

@dbuenzli I'm a bit confused by why this is. Currently odoc generated docs relies on `highlight.pack.js`. Wouldn't it be the same if we provide the custom js file in the repository and reference it when building docs?

**Comment by dbuenzli** [comment] 2019-02-25 16:03
> Currently odoc-generated docs relies on `highlight.pack.js`

Yes that's a global JavaScript file included on *all* pages generated by odoc.

> Wouldn't it be the same if we provide the custom js file in the repository and reference it when building docs?

You'd need to allow for pages to be generated with a reference to a custom `js` file and a convention for packages for where to install this file so that `odig` can pick it up.

I'm not sure it's worth the trouble and I personally highly prefer, in the `odig` context or a future `docs.ocaml.org`, if we don't allow packages to add their own JavaScript to their docs.

(Nowadays that the `file:` protocol executes js files, I wouldn't be against allowing a custom js file to be included from *themes* though, e.g. an `odoc.js` to be empty if there's nothing special you want to do, but that wouldn't solve your problem)

**Comment by tachukao** [comment] 2019-02-25 21:08
oh right I see what you mean. What I had in mind was also global JavaScript files that are included in all pages (e.g. to a local copy of mathjax.js or to a cdn). Having a custom JS file for each page would indeed be tedious and likely not worth the trouble.

**Comment by dbuenzli** [comment] 2019-02-25 21:30
> What I had in mind was also global JavaScript files that are included in all pages (e.g. to a local copy of mathjax.js or to a cdn).

Yes, and #123 is the right place to solve this (but please no cdn, some people care about offline/air gapped scenarios).

**Comment by tachukao** [comment] 2019-02-25 21:56
👍 sounds good, thanks!

**Comment by mseri** [comment] 2019-02-26 08:36
We'll move the discussion to #123

**Closed** 2019-02-26 08:35 UTC
Labels: command line, html

**Comment by vphantom** [comment] 2023-08-05 16:37
Out of curiosity, why is this issue closed? I can't find a way to pass `--theme-url` to `odoc`. There doesn't seem to be a way in `(documentation)` nor in profiles' `(odoc)`.

(My actual need is work around a bug at line 430 of `odoc.css` in the currently latest published version. I wanted to file a PR with `odoc` itself but their files are totally different now vs their latest release.)

**Comment by dbuenzli** [comment] 2023-08-05 18:10
That's a dune issue not an odoc issue. You'll have to open something there.
