### ISSUE TITLE
`odig doc` build of generated `.mld` failing (while odoc succeeds)

### ISSUE THREAD

**Issue by geoffder** [ocaml/odoc#922] opened 2023-01-08 00:31 UTC
I have just re-organized my doc build to include installing `odoc-assets` and using `_assets` in the hope of working both on my github hosted docs and in odig, yet one of my installed `.mld` files is not getting built into an html by odig.

The image at the top of my [index](https://geoffder.github.io/dometyl-keyboard/dometyl/index.html) correctly displays in the manual generated by installing from the [repo](https://github.com/geoffder/dometyl-keyboard) and running odig:

```
git clone https://github.com/geoffder/dometyl-keyboard
cd dometyl-keyboard
opam install .
odig doc dometyl
```
![image](https://user-images.githubusercontent.com/14910691/211173091-4abc67d1-6602-458c-a75a-be68a81a625e.png)

So at least I haven't screwed up my`odoc-assets` and `_assets` refactoring. However, the [walkthrough](https://geoffder.github.io/dometyl-keyboard/dometyl/walkthrough.html) page, which is generated by a rule attached to the `@doc` alias, does not appear (nor do the images also generated during `dune build @doc`, but as I have realized (while writing this), those aren't being installed with `opam install .`, so I have opened an issue at [dune](https://github.com/ocaml/dune/issues/6842) to learn why). Interestingly, `walkthrough.mld` does appear in `~/.opam/default/doc/dometyl/odoc-pages` and `~/.opam/default/var/cache/odig/html/dometyl/_doc-dir/odoc-pages`, but the `.html` does not appear `~/.opam/default/var/cache/odig/html/dometyl/` beside `index.html`.

Is there something that I am missing in the compatibility story with odoc and odig? Or is the html failing to build due to the missing image links (thus due to the install issue)?

**Comment by dbuenzli** [comment] 2023-01-08 10:55
Note this is rather an issue for [`odig`](https://github.com/b0-system/odig) (but I can't transfer it there).

It works here. I suspect the problem is that for now `odig doc PKG` will not update the docs unless the package is new (it's not fast enough to do it automatically for now) and you already had it installed. Do:

```
odig doc -u dometyl
```

<img width="649" alt="Screenshot 2023-01-08 at 11 45 42" src="https://user-images.githubusercontent.com/485596/211191841-0d631fdf-6e5e-4d4a-a24b-984de4e55855.png">

**Comment by geoffder** [comment] 2023-01-08 15:44
Oh wow I thought I opened this on odig, sorry! That's what I get for having too many tabs open. I can move it over soon if you'd like to still track it (if it should work without additional flags).

**Comment by dbuenzli** [comment] 2023-01-08 16:40
Well it's an edit distance of two, a perfectly reasonable slip for us humans. 

> I can move it over soon if you'd like to still track it (if it should work without additional flags).

No at the moment that's the way it going to work. It's [mentioned](https://erratique.ch/software/odig/doc/manual.html#odoc_docs) in the manual that likely no one reads.

I gather that your problem is solved so I'm going to close this. (btw. OSCADml looks cool I hope I once get some time to play with it)

**Closed by dbuenzli** 2023-01-08 16:40 UTC

**Comment by geoffder** [comment] 2023-01-08 18:24
>It's [mentioned](https://erratique.ch/software/odig/doc/manual.html#odoc_docs) in the manual that likely no one reads.

Guilty, other than the page about assets.

> (btw. OSCADml looks cool I hope I once get some time to play with it)

Thanks, I hope you do too. It's much harder to avoid things that you've made/contributed to, so thanks for that!
