### ISSUE TITLE
Unattached documentation comment (ignored)

### ISSUE THREAD

**Issue by Chris00** [ocaml/odoc#341] opened 2019-03-20 14:36 UTC
Steps to reproduce:
```shell
$ git clone https://github.com/Chris00/ocaml-mindstorm.git
$ cd ocaml-mindstorm/
$ git co 31ea1f7
$ dune build @doc
$ see _build/default/_doc/_html/mindstorm/Mindstorm/index.html 
```
The HTML rendering does not show the [final comment](https://github.com/Chris00/ocaml-mindstorm/blob/31ea1f7b788cc4899ce20c650c55d48f937ea98a/src/mindstorm.mli#L50).  Without the `[@@warning "-32"]`, the `dune build @doc` errors with the message:
 ```
Error (warning 50): unattached documentation comment (ignored)
```

**Comment by dbuenzli** [comment] 2019-03-20 14:46
Did you try to remove the final double semi [here](https://github.com/Chris00/ocaml-mindstorm/blob/31ea1f7b788cc4899ce20c650c55d48f937ea98a/src/mindstorm.mli#L211).

**Comment by Octachron** [comment] 2019-03-20 14:47
The problem is partially on the compiler side: the final `;;` is messing up the attachment of the comment, removing it (along with the `[@@warning ..]` item) fixes this issue.

**Comment by Chris00** [comment] 2019-03-20 15:04
Indeed removing `;;` does the trick!

**Comment by dbuenzli** [comment] 2019-09-01 09:10
@octachron should then something be filed upstream and this be closed ?

**Comment by Octachron** [comment] 2019-09-01 19:42
I think so, opening an issue on the compiler side asking for more informative error for unattached doc comment seems like a good idea. I may even have some time to look at the issue.

**Comment by aantron** [comment] 2020-05-09 04:42
@Octachron Is there an upstream issue for this now that we can link to? Closing the issue in this repo.

**Closed by aantron** 2020-05-09 04:42 UTC
Labels: bug
